import { TableType } from "../types/table";

// will be used for the dropdown in the new column form.
// for more options, see cell-types.tsx
export const dataTypes = [
  "String",
  "Boolean",
  "Number",
  "Time",
  "Week",
  "Range",
  "Month",
  "File",
  "Datetime",
  "Date",
  "Color",
] as const;

// this is the default data for the table.
export const tableData: TableType = {
  columns: [
    { id: "name", ordinalNo: 1, title: "Name", type: "string", width: 15 },
    { id: "age", ordinalNo: 2, title: "Age", type: "number", width: 5 },
    // add columns:
    { id: "city", ordinalNo: 3, title: "City", type: "string", width: 10 },
    {
      id: "country",
      ordinalNo: 4,
      title: "Country",
      type: "string",
      width: 10,
    },
    {
      id: "colorcode",
      ordinalNo: 5,
      title: "Color Code",
      type: "color",
      width: 10,
    },
    {
      id: "subscription",
      ordinalNo: 6,
      title: "Subscription",
      type: "select",
      width: 10,
    },
    {
      id: "joindate",
      ordinalNo: 7,
      title: "Join Date",
      type: "date",
      width: 10,
    },
    {
      id: "active",
      ordinalNo: 8,
      title: "Active",
      type: "boolean",
      width: 5,
    },
  ],
  data: [
    {
      id: "1",
      name: "Yossi Cohen",
      age: 15,
      city: "Tel Aviv",
      country: "Israel",
      colorcode: "#ff0000",
      subscription: ["Pro", "Free", "Basic", "Enterprise"],
      joindate: "2021-01-01",
      active: true,
    },
    {
      id: "2",
      name: "Rivka Levi",
      age: 25,
      city: "Jerusalem",
      country: "Israel",
      colorcode: "#00ff00",
      subscription: ["Basic", "Free", "Pro", "Enterprise"],
      joindate: "2021-11-11",
      active: false,
    },
    {
      id: "3",
      name: "David Mizrahi",
      age: 35,
      city: "Haifa",
      country: "Israel",
      colorcode: "#0000ff",
      subscription: ["Enterprise", "Free", "Basic", "Pro"],
      joindate: "2021-12-05",
      active: true,
    },
    {
      id: "4",
      name: "Yael Shapiro",
      age: 41,
      city: "Beersheba",
      country: "Israel",
      colorcode: "#ff00ff",
      subscription: ["Pro", "Free", "Basic", "Enterprise"],
      joindate: "2019-08-31",
      active: false,
    },
    {
      id: "5",
      name: "Moshe Katz",
      age: 53,
      city: "Netanya",
      country: "Israel",
      colorcode: "#00ffff",
      subscription: ["Basic", "Free", "Pro", "Enterprise"],
      joindate: "2020-01-01",
      active: false,
    },
    {
      id: "6",
      name: "Tamar Ben-David",
      age: 63,
      city: "Ashdod",
      country: "Israel",
      colorcode: "#ffff00",
      subscription: ["Enterprise", "Free", "Basic", "Pro"],
      joindate: "2020-12-31",
      active: true,
    },
    {
      id: "7",
      name: "Elior Peretz",
      age: 73,
      city: "Holon",
      country: "Israel",
      colorcode: "#ff00ff",
      subscription: ["Free", "Basic", "Pro", "Enterprise"],
      joindate: "2021-01-01",
      active: true,
    },
    {
      id: "8",
      name: "Sara Avraham",
      age: 83,
      city: "Bat Yam",
      country: "Israel",
      colorcode: "#00ff00",
      subscription: ["Basic", "Free", "Pro", "Enterprise"],
      joindate: "2021-11-11",
      active: false,
    },
    {
      id: "9",
      name: "Shlomi Aharon",
      age: 93,
      city: "Eilat",
      country: "Israel",
      colorcode: "#0000ff",
      subscription: ["Enterprise", "Free", "Basic", "Pro"],
      joindate: "2021-12-05",
      active: true,
    },
    {
      id: "10",
      name: "Michal Goldstein",
      age: 103,
      city: "Rehovot",
      country: "Israel",
      colorcode: "#ff0000",
      subscription: ["Pro", "Free", "Basic", "Enterprise"],
      joindate: "2019-08-31",
      active: true,
    },
  ],
};
